steps:
  # 1. Create a Docker image containing hadoop-connectors repo
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/dataproc-spark-spanner-connector-presubmit', '-f', 'cloudbuild/Dockerfile', '.']

  # 2. Fetch maven and dependencies
  - name: 'gcr.io/$PROJECT_ID/dataproc-spark-spanner-connector-presubmit'
    id: 'init'
    waitFor: ['docker-build']
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/presubmit.sh', 'init']

  # 3. Run integration tests with Spanner emulator
  - name: 'gcr.io/$PROJECT_ID/dataproc-spark-bigquery-connector-presubmit'
    id: 'integration-spanner-emulator'
    waitFor: ['init']
    entrypoint: 'bash'
    args: ['/workspace/cloudbuild/presubmit.sh', 'integrationtest-spanner-emulator']

timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_32'
