TEST_MUSIC_GRAPH_CC_VERTICES = \
"""
         property_name property_country_origin property_birthday property_ReleaseDate  __spark_spanner_connector_internal_id_node_table  __spark_spanner_connector_internal_id_key_column_AlbumId  __spark_spanner_connector_internal_id_key_column_CompanyId  __spark_spanner_connector_internal_id_key_column_SingerId
0        Cruz Richards                      US        1970-09-03                 None                                                 3                                                       NaN                                                         NaN                                                        1.0
1              Ice Ice                  Poland              None                 None                                                 2                                                       NaN                                                         4.0                                                        NaN
2           Ira Martin                      US        1991-11-09                 None                                                 3                                                       NaN                                                         NaN                                                        4.0
3        Izumi Trentor                      US        1991-10-02                 None                                                 3                                                       NaN                                                         NaN                                                        3.0
4         Mahan Lomond                      US        1977-01-29                 None                                                 3                                                       NaN                                                         NaN                                                        5.0
5          Mellow Wave                  U.S.A.              None                 None                                                 2                                                       NaN                                                         1.0                                                        NaN
6   Oint Is Not An Ink                    Peru              None                 None                                                 2                                                       NaN                                                         5.0                                                        NaN
7         Picky Penang                Malaysia              None                 None                                                 2                                                       NaN                                                         3.0                                                        NaN
8         Rolling Stow                  Canada              None                 None                                                 2                                                       NaN                                                         2.0                                                        NaN
9        Tristan Smith                      US        1990-08-17                 None                                                 3                                                       NaN                                                         NaN                                                        2.0
10                None                    None              None           2008-06-07                                                 1                                                       5.0                                                         NaN                                                        3.0
11                None                    None              None           2010-10-15                                                 1                                                       4.0                                                         NaN                                                        2.0
12                None                    None              None           2011-02-09                                                 1                                                       2.0                                                         NaN                                                        1.0
13                None                    None              None           2012-09-17                                                 1                                                       3.0                                                         NaN                                                        2.0
14                None                    None              None           2013-12-21                                                 1                                                       7.0                                                         NaN                                                        5.0
15                None                    None              None           2014-03-02                                                 1                                                       1.0                                                         NaN                                                        1.0
16                None                    None              None           2014-04-29                                                 1                                                       6.0                                                         NaN                                                        4.0
"""[1:-1]

TEST_MUSIC_GRAPH_CC_EDGES_SRC = \
"""
    property_SingerId property_release_date  property_FriendId  __spark_spanner_connector_internal_id_node_table  __spark_spanner_connector_internal_id_key_column_AlbumId  __spark_spanner_connector_internal_id_key_column_CompanyId  __spark_spanner_connector_internal_id_key_column_SingerId
0                 1.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        1.0
1                 1.0                  None                3.0                                                 3                                                       NaN                                                         NaN                                                        1.0
2                 1.0                  None                NaN                                                 3                                                       NaN                                                         NaN                                                        1.0
3                 2.0                  None                1.0                                                 3                                                       NaN                                                         NaN                                                        2.0
4                 2.0                  None                4.0                                                 3                                                       NaN                                                         NaN                                                        2.0
5                 2.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        2.0
6                 2.0                  None                NaN                                                 3                                                       NaN                                                         NaN                                                        2.0
7                 3.0                  None                1.0                                                 3                                                       NaN                                                         NaN                                                        3.0
8                 3.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        3.0
9                 3.0                  None                NaN                                                 3                                                       NaN                                                         NaN                                                        3.0
10                4.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        4.0
11                4.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        4.0
12                4.0                  None                NaN                                                 3                                                       NaN                                                         NaN                                                        4.0
13                5.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        5.0
14                5.0                  None                3.0                                                 3                                                       NaN                                                         NaN                                                        5.0
15                5.0                  None                4.0                                                 3                                                       NaN                                                         NaN                                                        5.0
16                5.0                  None                NaN                                                 3                                                       NaN                                                         NaN                                                        5.0
17                NaN            2008-06-07                NaN                                                 2                                                       NaN                                                         3.0                                                        NaN
18                NaN            2008-06-07                NaN                                                 3                                                       NaN                                                         NaN                                                        3.0
19                NaN            2010-10-15                NaN                                                 2                                                       NaN                                                         3.0                                                        NaN
20                NaN            2010-10-15                NaN                                                 3                                                       NaN                                                         NaN                                                        2.0
21                NaN            2011-02-09                NaN                                                 2                                                       NaN                                                         1.0                                                        NaN
22                NaN            2011-02-09                NaN                                                 3                                                       NaN                                                         NaN                                                        1.0
23                NaN            2012-09-17                NaN                                                 2                                                       NaN                                                         2.0                                                        NaN
24                NaN            2012-09-17                NaN                                                 3                                                       NaN                                                         NaN                                                        2.0
25                NaN            2013-12-21                NaN                                                 2                                                       NaN                                                         5.0                                                        NaN
26                NaN            2013-12-21                NaN                                                 3                                                       NaN                                                         NaN                                                        5.0
27                NaN            2014-03-02                NaN                                                 2                                                       NaN                                                         1.0                                                        NaN
28                NaN            2014-03-02                NaN                                                 3                                                       NaN                                                         NaN                                                        1.0
29                NaN            2014-04-29                NaN                                                 2                                                       NaN                                                         4.0                                                        NaN
30                NaN            2014-04-29                NaN                                                 3                                                       NaN                                                         NaN                                                        4.0
"""[1:-1]

TEST_MUSIC_GRAPH_CC_EDGES_DST = \
"""
    property_SingerId property_release_date  property_FriendId  __spark_spanner_connector_internal_id_node_table  __spark_spanner_connector_internal_id_key_column_AlbumId  __spark_spanner_connector_internal_id_key_column_CompanyId  __spark_spanner_connector_internal_id_key_column_SingerId
0                 1.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        2.0
1                 1.0                  None                3.0                                                 3                                                       NaN                                                         NaN                                                        3.0
2                 1.0                  None                NaN                                                 2                                                       NaN                                                         4.0                                                        NaN
3                 2.0                  None                1.0                                                 3                                                       NaN                                                         NaN                                                        1.0
4                 2.0                  None                4.0                                                 3                                                       NaN                                                         NaN                                                        4.0
5                 2.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        5.0
6                 2.0                  None                NaN                                                 2                                                       NaN                                                         2.0                                                        NaN
7                 3.0                  None                1.0                                                 3                                                       NaN                                                         NaN                                                        1.0
8                 3.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        5.0
9                 3.0                  None                NaN                                                 2                                                       NaN                                                         5.0                                                        NaN
10                4.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        2.0
11                4.0                  None                5.0                                                 3                                                       NaN                                                         NaN                                                        5.0
12                4.0                  None                NaN                                                 2                                                       NaN                                                         1.0                                                        NaN
13                5.0                  None                2.0                                                 3                                                       NaN                                                         NaN                                                        2.0
14                5.0                  None                3.0                                                 3                                                       NaN                                                         NaN                                                        3.0
15                5.0                  None                4.0                                                 3                                                       NaN                                                         NaN                                                        4.0
16                5.0                  None                NaN                                                 2                                                       NaN                                                         3.0                                                        NaN
17                NaN            2008-06-07                NaN                                                 1                                                       5.0                                                         NaN                                                        3.0
18                NaN            2008-06-07                NaN                                                 1                                                       5.0                                                         NaN                                                        3.0
19                NaN            2010-10-15                NaN                                                 1                                                       4.0                                                         NaN                                                        2.0
20                NaN            2010-10-15                NaN                                                 1                                                       4.0                                                         NaN                                                        2.0
21                NaN            2011-02-09                NaN                                                 1                                                       2.0                                                         NaN                                                        1.0
22                NaN            2011-02-09                NaN                                                 1                                                       2.0                                                         NaN                                                        1.0
23                NaN            2012-09-17                NaN                                                 1                                                       3.0                                                         NaN                                                        2.0
24                NaN            2012-09-17                NaN                                                 1                                                       3.0                                                         NaN                                                        2.0
25                NaN            2013-12-21                NaN                                                 1                                                       7.0                                                         NaN                                                        5.0
26                NaN            2013-12-21                NaN                                                 1                                                       7.0                                                         NaN                                                        5.0
27                NaN            2014-03-02                NaN                                                 1                                                       1.0                                                         NaN                                                        1.0
28                NaN            2014-03-02                NaN                                                 1                                                       1.0                                                         NaN                                                        1.0
29                NaN            2014-04-29                NaN                                                 1                                                       6.0                                                         NaN                                                        4.0
30                NaN            2014-04-29                NaN                                                 1                                                       6.0                                                         NaN                                                        4.0
"""[1:-1]
